name: Build and Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build binaries
        run: |
          GOOS=linux GOARCH=386 go build -o bin/gpt_cmd-linux-386
          GOOS=linux GOARCH=amd64 go build -o bin/gpt_cmd-linux-amd64
          GOOS=linux GOARCH=arm go build -o bin/gpt_cmd-linux-arm
          GOOS=linux GOARCH=arm64 go build -o bin/gpt_cmd-linux-arm64

          GOOS=darwin GOARCH=amd64 go build -o bin/gpt_cmd-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o bin/gpt_cmd-darwin-arm64

          GOOS=windows GOARCH=386 go build -o bin/gpt_cmd-windows-386.exe
          GOOS=windows GOARCH=amd64 go build -o bin/gpt_cmd-windows-amd64.exe
      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: 'bin/*'
